### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by fatse**

### CODE REVIEW

**Comment by nphaterp** [comment]
Im good with this.

**Review by nphaterp — APPROVED** [review]

**Comment by tanmaysharma19** [comment]
Do we want to change the first line which says `MIT License` to something like `DSCI-522 Group 24 License` and instead acknowledge the source at the bottom?

**Comment by fatse** [comment]
@tanmaysharma19 I don't think so. An MIT license should look exactly like that. 

Also, Tiffany suggested using the MIT license if we don't have a preferred one.
> re: You may have noticed when you create a new repo on GitHub, you're asked to set a license for your project. If you do not currently have a preference, we recommend you use the [MIT license](https://choosealicense.com/licenses/mit/) for your project.

Besides, I used the GitHub automated tool to automatically generate an MIT license. For more details see this: https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/adding-a-license-to-a-repository
In [step 5](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/adding-a-license-to-a-repository) I chose the MIT license.

**Comment by tanmaysharma19** [comment]
@fatse that makes sense. Thank you for explaining.

**Pull request merged**
