### PR TITLE
Created Script4 

### PR DESCRIPTION
**Pull request by nphaterp**

### CODE REVIEW

**Comment by nphaterp** [comment]
still trying to figure out why my README files are changed, will fix

**Comment by nphaterp** [comment]
Just finished creating script4 with the help of Fatime. We are still trying to find ways to improve the visual aesthetics of the tables. But the script functions properly now.

**Comment by fatse** [comment]
The code looks good to me, good job Neel! 👏 

One suggestion: Can we create a new PR that contains only the changes for Script 4? 
Looks like this PR is changing the README.md file as well as creating a new `.Rmd` file for Script 4. Usually, PR should include only the files specific to that task. 
In this case, I would:
`git switch main`
`git fetch main_repo`  
`git rebase main_repo/main`
`git switch -c script-4`

Then create a new `.R` script (copy-paste everything you have in this PR in `script4.R`).
Also, create a new `results` folder in the root directory which will contain the output from your script.
Finally, commit those changes, push them, and create a new PR that will have only changes relevant to this task.

Let me know what you think.

P.S. Seems like this PR has conflicts anyway, so a new PR would save you from the hassle of resolving the conflicts.

**Comment by nphaterp** [comment]
Closing and creating a new PR because I did not pull before creating this branch

**Pull request closed without merging**
