### PR TITLE
Add .gitignore file to the project root directory

### PR DESCRIPTION
**Pull request by fatse**

### CODE REVIEW

**Review by tanmaysharma19 — CHANGES_REQUESTED** [review]
Could you also please add __pycache__/ or *cache/.
Thank you.

**Comment by fatse** [comment]
@tanmaysharma19 `*_cache/` and `/cache/` are already added to the .gitignore file, see line 11-12.

For the reference: https://github.com/UBC-MDS/dsci-522-group-24/pull/13/files#diff-bc37d034bad564583790a46f19d807abfe519c5671395fd494d8cce506c42947R11

But I'll add `__pycache__/` 😊

**Comment by fatse** [comment]
`__pycache__` added to .gitignore file. 
@tanmaysharma19 thanks for the suggestion and prompt CR.

**Comment by tanmaysharma19** [comment]
Looks good, thank you.

**Pull request merged**
