### PR TITLE
Modify README.md. Add README.Rmd

### PR DESCRIPTION
**Pull request by fatse**
Hi guys 🇨🇦  🇺🇸 

There are a lot of changes in this commit, such as:

- Modify README.md - add introduction, usage, dependencies, license, and references sections. 
- Add README.rmd file with introduction, usage, ependencies, license, and references sections
- Add parsed bibliography using pandoc.
- Add bibtex file under doc folder.
- Delete extra python and R script that downloads the data. 
- Add .csv file to the processed folder under data.  
- Update .gitignore - add .Rproj to ignore R generated files

I would appreciate your review/feedback on this PR.

Thanks!

### CODE REVIEW

**Comment by tanmaysharma19** [comment]
- Should we add a line about both the EDA reports in the Readme.md as per #18 ?

**Comment by fatse** [comment]
@tanmaysharma19 where would you prefer to add the pointer about both the EDA reports?

**Comment by tanmaysharma19** [comment]
@fatse - In the Readme.md in the paragraph that says, "We will create a summary table..."

We can append a line at the starting that says, "We will perform an EDA using best practices to explore our dataset. We would be carrying out an EDA using both R and Python to understand our data better. Based on our EDA, we will create a summary table..."

What say?

**Comment by nichowu** [comment]
Sorry, I don't think Fatime's README.md file includes Neel's most up-to-date proposal. Could either of you take a another look and update it? 

One more thing: Looking at the updated standard deviation both Tanmay and I calculated, it seems "equal variance" assumption is not met (see attached). So t-test is out. I guess we can do a permutation test? Can you update it in the proposal as well? I think Neel's most up-to-date proposal mentioned t-test. 

image

**Comment by nichowu** [comment]
Everything else in the PR is good with me. Thanks!

**Comment by fatse** [comment]
@tanmaysharma19 @nphaterp @nichowu 

The line suggested by @tanmaysharma19 above has been added in the README - Introduction section and README has been updated to reflect the latest changes made in the proposal.Rmd by @nphaterp.

These changes have been captured in commit `a1b84189dec39f8cec4f44cacdb1de0f8e23d28a` in my PR.

**Comment by nphaterp** [comment]
Im good with this,.  Maybe @nichowu  once you take a final look you can merge ?

**Pull request merged**
